name: Tests front

on:
  push:
    branches: [ "main", "dev/*" ]
  pull_request:
    branches: [ "main", "dev/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front 

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - run: npm ci
    - run: npm test -- --browsers=ChromeHeadless --watch=false --code-coverage
